-- MySQL Script generated by MySQL Workbench
-- Wed Mar 28 14:54:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `idrol` INT NOT NULL,
  `NombreRol` VARCHAR(45) NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Primer Nombre` VARCHAR(45) NULL,
  `Segundo Nombre` VARCHAR(45) NULL,
  `Primer Apellido` VARCHAR(45) NULL,
  `Segundo Apellido` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `rol_idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_de_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo_de_evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_de_evento` (
  `idTipo_de_evento` INT NOT NULL,
  `Nombre_tipo` VARCHAR(45) NULL,
  `Descripcion_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_de_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL,
  `Nombre_Evento` VARCHAR(45) NULL,
  `Descripcion_evento` VARCHAR(45) NULL,
  `Cronograma` VARCHAR(45) NULL,
  `Fecha_inicio` DATE NULL,
  `Fecha_fin` DATE NULL,
  `Tipo_de_evento_idTipo_de_evento` INT NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Certificado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Certificado` (
  `idCertificado` INT NOT NULL,
  `Nombre_cer` VARCHAR(45) NULL,
  `Descripcion_cer` VARCHAR(45) NULL,
  PRIMARY KEY (`idCertificado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `idPago` INT NOT NULL,
  `Cantidad` INT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_has_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento_has_Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento_has_Usuario` (
  `Evento_idEvento` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Certificado_idCertificado` INT NOT NULL,
  `Pago_idPago` INT NOT NULL,
  PRIMARY KEY (`Evento_idEvento`, `Usuario_idUsuario`, `Certificado_idCertificado`, `Pago_idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Precio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Precio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Precio` (
  `idPrecio` INT NOT NULL,
  `Valor_pago` INT NULL,
  PRIMARY KEY (`idPrecio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_has_Precio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento_has_Precio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento_has_Precio` (
  `Evento_idEvento` INT NOT NULL,
  `Precio_idPrecio` INT NOT NULL,
  PRIMARY KEY (`Evento_idEvento`, `Precio_idPrecio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sitio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sitio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sitio` (
  `idSitio` INT NOT NULL,
  `Nombre_sitio` VARCHAR(45) NULL,
  `Direccion_sitio` VARCHAR(45) NULL,
  `Telefono_sitio` VARCHAR(45) NULL,
  `sala_idsala` INT NULL,
  PRIMARY KEY (`idSitio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recurso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recurso` (
  `idRecurso` INT NOT NULL,
  `Nombre_recurso` VARCHAR(45) NULL,
  `Descrpcion_recurso` VARCHAR(45) NULL,
  `Cantida_recurso` INT NULL,
  PRIMARY KEY (`idRecurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_has_Sitio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento_has_Sitio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento_has_Sitio` (
  `Evento_idEvento` INT NOT NULL,
  `Sitio_idSitio` INT NOT NULL,
  `Recurso_idRecurso` INT NOT NULL,
  `Descripcion_sitio` VARCHAR(45) NULL,
  PRIMARY KEY (`Evento_idEvento`, `Sitio_idSitio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permisos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `Modulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permisos_has_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permisos_has_rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permisos_has_rol` (
  `Permisos_idPermisos` INT NOT NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`Permisos_idPermisos`, `rol_idrol`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
